- type: job
  id: BoSWestElderCommander
  setPreference: true
  name: job-name-bos-west-elder-comm
  description: job-description-bos-west-elder-comm
  playTimeTracker: BoSWestElderCommander
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
    - !type:CharacterDepartmentTimeRequirement
      department: BrotherhoodWest
      min: 216000 # 60 hours
    - !type:CharacterPlaytimeRequirement
      tracker: BoSWestPaladin
      min: 43200 # 12 hours
  startingGear: BoSWestElderCommanderGear
  alwaysUseSpawner: true
  icon: "JobIconBosMCommander"
  supervisors: job-supervisors-bos-west-elder
  canBeAntag: false
  accessGroups:
  - BoSWest
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodWest

- type: startingGear
  id: BoSWestElderCommanderGear
  equipment:
    jumpsuit: N14ClothingUniformBosReconWest
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsCombatFilled
    head:  N14ClothingHeadHatBrotherhoodFieldCap
    outerClothing: N14ClothingOuterPowerArmorT51Elder
    hands: N14ClothingHandsGlovesCombat
    pocket1: BoSWesternEldenKits
    id: N14IDBrotherhoodWestHolotagElderCommander
    ears: N14ClothingHeadsetBOSWest
    belt: N14ClothingBeltBoSWesternKhignht
  storage:
    back:
    - N14BoxPlasticFilledMilitary

- type: playTimeTracker
  id: BoSWestElderCommander
