- type: job
  id: BoSWestGunsmith
  setPreference: true
  name: job-name-bos-west-gunsmith
  description: job-description-bos-west-gunsmith
  playTimeTracker: BoSWestGunsmith
  requirements:
    - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterSpeciesRequirement
          species:
            - Human
    - !type:CharacterOverallTimeRequirement
      min: 3600
  startingGear: BoSWestGunsmithGear
  alwaysUseSpawner: true
  icon: "JobIconBosMSquire"
  supervisors: job-supervisors-bos-west-initiate
  canBeAntag: false
  access:
  - BoSWest
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodWest

- type: startingGear
  id: BoSWestGunsmithGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSWestScout
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsCombatFilled
    head: N14ClothingHeadHatCapScout
    outerClothing: N14ClothingOuterRecruitWesternArmor
    pocket1: BoSWesternSquireKits
    id: N14IDBrotherhoodWestHolotagGunsmith
    belt: N14ClothingBeltBosLeatherunl
  storage:
    back:
    - N14BoxPlasticFilledMilitary

- type: playTimeTracker
  id: BoSWestGunsmith
